=== FlooferLand/wplace-art/metadataSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/GeneratorMetadata",
    "definitions": {
        "GeneratorMetadata": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "credits": {
                    "type": "object",
                    "properties": {
                        "authors": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "description": "The maintainers / helpers of the drawing"
                        },
                        "artists": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "description": "The people who actually made the art"
                        },
                        "additional": {
                            "type": "string",
                            "description": "Any additional credits"
                        }
                    },
                    "required": [
                        "authors"
                    ],
                    "additionalProperties": false
                },
                "license": {
                    "type": "string"
                },
                "png": {
                    "type": "string"
                },
                "tile": {
                    "type": "string"
                },
                "coords": {
                    "type": "object",
                    "properties": {
                        "link": {
                            "type": "string",
                            "description": "The Wplace link"
                        },
                        "top_left": {
                            "type": "object",
                            "properties": {
                                "x": {
                                    "type": "number"
                                },
                                "y": {
                                    "type": "number"
                                }
                            },
                            "required": [
                                "x",
                                "y"
                            ],
                            "additionalProperties": false,
                            "description": "The top left pixel"
                        }
                    },
                    "required": [
                        "link",
                        "top_left"
                    ],
                    "additionalProperties": false
                }
            },
            "required": [
                "name",
                "credits",
                "png",
                "coords"
            ],
            "additionalProperties": false
        }
    }
}

=== FlooferLand/wplace-art/vapie/data/metadata.json
{
    "name": "Vapie",
    "credits": {
        "authors": ["FlooferLand (RO) #5674026"],
        "artists": ["FlooferLand (RO)#5674026"],
        "additional": "Original design by Nintendo"
    },
    "coords": {
        "link": "TODO",
        "top_left": { "x": -1, "y": -1 }
    },
    "png": "wplace_vapie.png",
    "license": "CC-BY-4.0"
}

=== FlooferLand/wplace-art/scav_creature/data/metadata.json
{
    "name": "Scav Prototype creature",
    "credits": {
        "authors": ["TrueChaos #4309268"],
        "artists": ["TrueChaos #4309268"],
        "additional": "Original design from Scav Prototype"
    },
    "coords": {
        "link": "TODO",
        "top_left": { "x": 1584, "y": 3137 }
    },
    "png": "scav_creature.png"
}
